In [17]:
# install notebook scheduler 
#pip install jupyter_scheduler

In [40]:
import pandas as pd

In [41]:
# Lets assume import data core system archived files that are not support in current data models
df = pd.read_csv('C:\\Users\\Lenovo\\Documents\\Jupyter Notebook\\credit_risk_dataset.csv')
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [42]:
from datetime import datetime

# current datetime and format it as 'MM-DD-YYYY HH-MM-SS'
timestamp = datetime.now().strftime('%m-%d-%Y %H-%M-%S')
# define filename with timestamp
filename = f'exported_data_{timestamp}.csv'

In [43]:
output_path = f'C:\\Users\\Lenovo\\Documents\\Jupyter Notebook\\output\\{filename}'
df.to_csv(output_path, index=False)

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4